FROM node:lts-alpine AS dev

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV CHOKIDAR_USEPOLLING=true
ENV HOST=0.0.0.0

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host=0.0.0.0", "--port=4200", "--poll=3000", "--disable-host-check"]
