version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    networks:
      - backend-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - backend-net
    command: python manage.py runserver 0.0.0.0:8000

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile-frontend
#    depends_on:
#      - backend
#    ports:
#      - "8080:80"
#    networks:
#      - backend-net

volumes:
  dbdata:

networks:
  backend-net:
    driver: bridge
