# backend/Dockerfile-backend
FROM python:3.11-slim

# Install system dependencies for psycopg2
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project code
COPY . .

# Collect static files (jeśli wykorzystywane)
RUN python manage.py collectstatic --noinput

# Uruchomienie aplikacji przez Gunicorn
CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"]