FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential libpq-dev curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT ["bash", "-c"]
CMD ["python manage.py collectstatic --noinput && \
      python manage.py migrate && \
      python manage.py create_superuser && \
      gunicorn --bind 0.0.0.0:8000 --timeout 500 --reload core.wsgi:application "]
