# Generated by Django 5.2.4 on 2025-07-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    def create_default_categories(apps, schema_editor):
        EventCategory = apps.get_model("event_scheduler", "EventCategory")
        for name in ["Cat1", "Cat2", "Cat3"]:
            EventCategory.objects.get_or_create(name=name)

    dependencies = [
        ("event_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
